In [1]:
import tensorflow as tf

In [2]:
mnist = tf.keras.datasets.mnist

(x_train, y_train), (x_test, y_test) = mnist.load_data()
x_train, x_test = x_train / 255.0, x_test / 255.0


In [3]:
model = tf.keras.models.Sequential([
  tf.keras.layers.Flatten(input_shape=(28, 28)),
  tf.keras.layers.Dense(128, activation='relu'),
  tf.keras.layers.Dropout(0.2),
  tf.keras.layers.Dense(10)
])

In [4]:
predictions = model(x_train[:1]).numpy()
predictions


If you intended to run this layer in float32, you can safely ignore this warning. If in doubt, this warning is likely only an issue if you are porting a TensorFlow 1.X model to TensorFlow 2.

To change all layers to have dtype float64 by default, call `tf.keras.backend.set_floatx('float64')`. To change just this layer, pass dtype='float64' to the layer constructor. If you are the author of this layer, you can disable autocasting by passing autocast=False to the base Layer constructor.



array([[ 0.48206657,  0.1789599 ,  0.33012152, -0.74873984,  0.1935893 ,
        -0.39258116,  0.3242105 ,  0.76938885,  0.17939588, -0.4287464 ]],
      dtype=float32)

In [5]:
x_train[:1].shape

(1, 28, 28)

In [6]:
tf.nn.softmax(predictions).numpy()

array([[0.13542993, 0.10001776, 0.11633912, 0.03955326, 0.10149171,
        0.05647549, 0.11565346, 0.18050829, 0.10006137, 0.05446953]],
      dtype=float32)

In [7]:
loss_fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)
loss_fn(y_train[:1], predictions).numpy()


2.8739486

In [13]:
model.compile(optimizer='adam',
              loss=loss_fn,
              metrics=['accuracy'])


In [14]:
model.fit(x_train, y_train, epochs=5)


ValueError: A target array with shape (60000, 1) was passed for an output of shape (None, 10) while using as loss `mean_squared_error`. This loss expects targets to have the same shape as the output.

In [10]:
model.evaluate(x_test,  y_test, verbose=2)

10000/10000 - 0s - loss: 0.0821 - accuracy: 0.9750


[0.08206156437145547, 0.975]

In [11]:
probability_model = tf.keras.Sequential([
  model,
  tf.keras.layers.Softmax()
])

In [12]:
probability_model(x_test[:5])

<tf.Tensor: shape=(5, 10), dtype=float32, numpy=
array([[2.42816949e-08, 1.23884636e-09, 2.24184569e-05, 3.16149264e-04,
        1.17120327e-10, 3.81670375e-08, 1.77592819e-11, 9.99612391e-01,
        6.12464305e-07, 4.83789954e-05],
       [1.05487182e-07, 7.93076833e-06, 9.99894977e-01, 8.60372384e-05,
        2.16987191e-14, 8.14024247e-07, 2.51931738e-08, 1.17692173e-12,
        1.01666574e-05, 1.01284580e-11],
       [1.01937374e-07, 9.98629808e-01, 1.32400179e-04, 1.59737319e-05,
        2.60490469e-05, 1.55340274e-06, 1.90013234e-05, 1.09431497e-03,
        7.70328988e-05, 3.75330819e-06],
       [9.99756992e-01, 1.15237719e-09, 1.92909511e-06, 1.99236112e-08,
        1.01512732e-07, 1.43759173e-08, 1.81907410e-04, 8.20427772e-07,
        7.21724414e-09, 5.82455468e-05],
       [7.65638902e-07, 1.29586369e-10, 5.36347443e-07, 9.50456069e-09,
        9.98961568e-01, 4.28452509e-08, 4.03533204e-06, 1.19132701e-05,
        4.52994414e-07, 1.02066598e-03]], dtype=float32)>

In [23]:
y_test.shape

(10000,)

In [24]:
y_test

array([7, 2, 1, ..., 4, 5, 6], dtype=uint8)